# SIB - Intelligent Systems for Bioinformatics

### Exercise 2: NumPy array Indexing/Slicing

Examples of how to use the methods in exercise 2

- Method name: dropna

In [5]:
import numpy as np
from si.data.dataset import Dataset

In [9]:
X = np.array([[1, 2, np.nan],
              [3, 4, 5],
              [np.nan, 6, 7]])
y = np.array([10, 20, 30])
dataset = Dataset(X, y,label="Y")

print("Features values with missing values:\n",dataset.X)
print("Lables with missing values:",dataset.y)
print("Shape of X with missing values:",dataset.X.shape)
print("Shape of Y with missing values:",dataset.y.shape)

dataset = dataset.dropna()

print("Shape of X without missing values:",dataset.X.shape)
print("Shape of y without missing values:",dataset.y.shape)
print("Features values without missing values:\n",dataset.X)
print("Labels without missing values:",dataset.y)

Features values with missing values:
 [[ 1.  2. nan]
 [ 3.  4.  5.]
 [nan  6.  7.]]
Lables with missing values: [10 20 30]
Shape of X with missing values: (3, 3)
Shape of Y with missing values: (3,)
Shape of X without missing values: (1, 3)
Shape of y without missing values: (1,)
Features values without missing values:
 [[3. 4. 5.]]
Labels without missing values: [20]


- Method name: fillna

In [12]:
X = np.array([[30, 2, np.nan],
                  [3, 4, 5],
                  [np.nan, 6, 7]])
y = np.array([10, 20, 30])
dataset= Dataset(X, y)

print(dataset.X)
print("Median:",dataset.get_median())

dataset_median = dataset.fillna(value="median")

print("Features values with missing values equal to the mean:\n",dataset_median.X)

[[30.  2. nan]
 [ 3.  4.  5.]
 [nan  6.  7.]]
Median: [16.5  4.   6. ]


AttributeError: 'Dataset' object has no attribute 'fillna'

- Method name: remove_by_index

In [11]:
X = np.array([[30, 2, np.nan],
                  [3, 4, 5],
                  [np.nan, 6, 7]])
y = np.array([10, 20, 30])
dataset= Dataset(X, y)

print(dataset.X)

dataset_ = dataset.remove_by_index(index= 1)

print("\n",dataset.X)

[[30.  2. nan]
 [ 3.  4.  5.]
 [nan  6.  7.]]


AttributeError: 'Dataset' object has no attribute 'remove_by_index'