# SIB - Intelligent Systems for Bioinformatics

### Exercise 1: NumPy array Indexing/Slicing

1.1) In this exercise, we will use the iris dataset. Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).

In [16]:
from si.io.csv_file import read_csv

# Loading the dataset iris.csv
iris_dataset = read_csv('../datasets/iris/iris.csv', features=True, label=True)

# Display information about the loaded dataset
print("Shape of iris dataset:", iris_dataset.shape())
print(iris_dataset.X)
print("Features:", iris_dataset.features)
print("Label:", iris_dataset.label)

Shape of iris dataset: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]

1.2) Select the penultimate independent variable. What is the dimension of the resulting array?

In [ ]:
# Select the penultimate independent variable
pen_variable = iris_dataset.X[:, -2]

# Determine the size of the resulting array
Number_of_dimensions = pen_variable.ndim
Shape = pen_variable.shape

print("Number of dimensions:", Number_of_dimensions)
print("Shape:", Shape)


Number of dimensions: 1
Shape: (150,)


1.3) Select the last 10 samples from the iris dataset. What is the mean of the last 10 samples for each independent variable/feature?

In [18]:
import numpy as np

# Select the last 10 samples
last_10_samples = iris_dataset.X[-10:, :]

# Calculate the mean of each independent variable
average_per_variable = np.mean(last_10_samples, axis=0)
print("Average per variable:", average_per_variable)

Average per variable: [6.45 3.03 5.33 2.17]


1.4) Select all samples from the dataset with values less than or equal to 6 for all independent variables/features. How many samples do you obtain?

In [20]:
# Boolean mask where each element indicates whether the condition is met
mask_samples = iris_dataset.X <= 6

# Identify the samples where all the features meet the condition
selected_samples = np.all(mask_samples, axis=1)

# Select the samples that meet the criteria
filtered_samples = iris_dataset.X[selected_samples]

# Determine the number of samples selected
number_samples  = filtered_samples.shape[0]

print(f"Number of samples where all independent variables are ≤ 6: {number_samples }")


Number of samples where all independent variables are ≤ 6: 89


1.5) Select all samples with a class/label different from 'Iris-setosa'. How many samples do you obtain?

In [24]:
# Boolean mask for samples with labels other than 'Iris-setosa'
mask_not_iris_setosa = iris_dataset.y != 'Iris-setosa'

# Select the samples that meet the criteria
samples_not_setosa = iris_dataset.X[mask_not_iris_setosa]

print(f"Number of samples with a label other than 'Iris-setosa': {samples_not_setosa.shape[0]}")

Number of samples with a label other than 'Iris-setosa': 100
